#! /bin/sh
#
# Copyright © 2011 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
export PATH=".:tests:${PATH}"

rm -f WatchMe watch-results

# watchfile is like tail -f
watchfile WatchMe > watch-results &
pid=$!

trap "kill ${pid} >/dev/null 2>&1 || true" EXIT

sleep 1                         # allow watchfile to start up

echo one > WatchMe
echo two >> WatchMe
echo sleeping...
sleep 1
diff -U20 ${srcdir:-.}/watch-expect-1 watch-results

echo renaming...
mv WatchMe DontWatchMe
echo sleeping...
sleep 1
diff -U20 ${srcdir:-.}/watch-expect-2 watch-results

echo three >> DontWatchMe

echo four > WatchMe
echo five >> WatchMe
echo sleeping...
sleep 1
diff -U20 ${srcdir:-.}/watch-expect-3 watch-results

echo renaming back...
mv DontWatchMe WatchMe
echo sleeping...
sleep 1
diff -U20 ${srcdir:-.}/watch-expect-4 watch-results

echo redirecting...
exec 3>>WatchMe
echo removing...
rm -f WatchMe
echo sleeping...
sleep 1
diff -U20 ${srcdir:-.}/watch-expect-5 watch-results # trouble: intermittently get an extra one two three

echo six >&3

echo sleeping...
sleep 1                         # allow watchfile to flush buffers
diff -U20 ${srcdir:-.}/watch-expect-6 watch-results

echo killing...
kill ${pid}
diff -U20 ${srcdir:-.}/watch-expect-7 watch-results
