#! /bin/sh
#
# Copyright © 2011 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
export PATH=".:tests:${PATH}"

rm -f WatchMe watch-results

watchfile WatchMe > watch-results &
pid=$!

trap "kill ${pid} >/dev/null 2>&1 || true" EXIT INT HUP TERM

sleep 1                         # allow watchfile to start up

echo one > WatchMe
echo two >> WatchMe
sleep 1

mv WatchMe DontWatchMe
sleep 1

echo three >> DontWatchMe

echo four > WatchMe
echo five >> WatchMe
sleep 1

mv DontWatchMe WatchMe
sleep 1

exec 3>>WatchMe
rm -f WatchMe
sleep 1

echo six >&3

sleep 1                         # allow watchfile to flush buffers
kill ${pid}

diff -u ${srcdir:-.}/watch-expect watch-results
